// מאגר כל צמדי האימוג'י והמילים באנגלית עבור האפליקציה "Say the word"

(function(global) {
  const PAIRS = [
  ["🐶","dog"],
  ["🐱","cat"],
  ["🐭","mouse"],
  ["🐹","hamster"],
  ["🐰","rabbit"],
  ["🦊","fox"],
  ["🐻","bear"],
  ["🐼","panda"],
  ["🐨","koala"],
  ["🐯","tiger"],
  ["🦁","lion"],
  ["🐮","cow"],
  ["🐷","pig"],
  ["🐸","frog"],
  ["🐵","monkey"],
  ["🐔","chicken"],
  ["🐧","penguin"],
  ["🐦","bird"],
  ["🐤","chick"],
  ["🦆","duck"],
  ["🦉","owl"],
  ["🦇","bat"],
  ["🐺","wolf"],
  ["🐗","boar"],
  ["🐴","horse"],
  ["🦄","unicorn"],
  ["🐝","bee"],
  ["🦋","butterfly"],
  ["🐛","bug"],
  ["🐌","snail"],
  ["🐞","ladybug"],
  ["🐜","ant"],
  ["🪲","beetle"],
  ["🐢","turtle"],
  ["🐍","snake"],
  ["🦎","lizard"],
  ["🐙","octopus"],
  ["🦑","squid"],
  ["🦐","shrimp"],
  ["🦞","lobster"],
  ["🦀","crab"],
  ["🐟","fish"],
  ["🐬","dolphin"],
  ["🐳","whale"],
  ["🦈","shark"],
  ["🐊","crocodile"],
  ["🐆","leopard"],
  ["🦓","zebra"],
  ["🦍","gorilla"],
  ["🦧","orangutan"],
  ["🐘","elephant"],
  ["🦛","hippo"],
  ["🦏","rhino"],
  ["🐪","camel"],
  ["🦒","giraffe"],
  ["🦘","kangaroo"],
  ["🦬","bison"],
  ["🐂","ox"],
  ["🐏","ram"],
  ["🐑","sheep"],
  ["🦙","llama"],
  ["🐐","goat"],
  ["🦌","deer"],
  ["🐩","poodle"],
  ["🐓","rooster"],
  ["🦃","turkey"],
  ["🦚","peacock"],
  ["🦜","parrot"],
  ["🦢","swan"],
  ["🦩","flamingo"],
  ["🕊️","dove"],
  ["🦝","raccoon"],
  ["🦨","skunk"],
  ["🦡","badger"],
  ["🦦","otter"],
  ["🦥","sloth"],
  ["🦔","hedgehog"],
  ["🍎","apple"],
  ["🍐","pear"],
  ["🍊","orange"],
  ["🍋","lemon"],
  ["🍌","banana"],
  ["🍉","watermelon"],
  ["🍇","grapes"],
  ["🍓","strawberry"],
  ["🫐","blueberry"],
  ["🍒","cherry"],
  ["🍑","peach"],
  ["🥭","mango"],
  ["🍍","pineapple"],
  ["🥥","coconut"],
  ["🥝","kiwi"],
  ["🍅","tomato"],
  ["🍆","eggplant"],
  ["🥑","avocado"],
  ["🥦","broccoli"],
  ["🥒","cucumber"],
  ["🌶️","pepper"],
  ["🌽","corn"],
  ["🥕","carrot"],
  ["🫒","olive"],
  ["🧄","garlic"],
  ["🧅","onion"],
  ["🥔","potato"],
  ["🍞","bread"],
  ["🥨","pretzel"],
  ["🧀","cheese"],
  ["🥚","egg"],
  ["🧈","butter"],
  ["🥞","pancake"],
  ["🧇","waffle"],
  ["🥓","bacon"],
  ["🥩","steak"],
  ["🍗","drumstick"],
  ["🌭","hotdog"],
  ["🍔","burger"],
  ["🍟","fries"],
  ["🍕","pizza"],
  ["🥪","sandwich"],
  ["🌮","taco"],
  ["🌯","burrito"],
  ["🧆","falafel"],
  ["🥗","salad"],
  ["🍝","pasta"],
  ["🍜","noodles"],
  ["🍲","soup"],
  ["🍛","curry"],
  ["🍣","sushi"],
  ["🥟","dumpling"],
  ["🦪","oyster"],
  ["🍚","rice"],
  ["🥧","pie"],
  ["🧁","cupcake"],
  ["🎂","cake"],
  ["🍭","lollipop"],
  ["🍬","candy"],
  ["🍫","chocolate"],
  ["🍿","popcorn"],
  ["🍩","donut"],
  ["🍪","cookie"],
  ["🥜","peanut"],
  ["🍯","honey"],
  ["🥛","milk"],
  ["☕","coffee"],
  ["🍵","tea"],
  ["🧃","juice"],
  ["🧊","ice"],
  ["🥄","spoon"],
  ["🍴","fork"],
  ["🥣","bowl"],
  ["☀️","sun"],
  ["🌙","moon"],
  ["⭐","star"],
  ["🌈","rainbow"],
  ["☁️","cloud"],
  ["❄️","snow"],
  ["🔥","fire"],
  ["💧","water"],
  ["🌊","wave"],
  ["🌸","flower"],
  ["🌼","daisy"],
  ["🌻","sunflower"],
  ["🌺","hibiscus"],
  ["🌹","rose"],
  ["🌷","tulip"],
  ["🌱","seed"],
  ["🌳","tree"],
  ["🌴","palm"],
  ["🌵","cactus"],
  ["🍀","clover"],
  ["🍁","leaf"],
  ["🌍","earth"],
  ["🏠","house"],
  ["🏫","school"],
  ["🏥","hospital"],
  ["🏰","castle"],
  ["⛺","tent"],
  ["🚗","car"],
  ["🚕","taxi"],
  ["🚌","bus"],
  ["🚜","tractor"],
  ["🚲","bike"],
  ["🛴","scooter"],
  ["✈️","plane"],
  ["🚀","rocket"],
  ["🚁","helicopter"],
  ["⛵","boat"],
  ["🚢","ship"],
  ["🚂","train"],
  ["⚽","ball"],
  ["🏀","basketball"],
  ["🏈","football"],
  ["⚾","baseball"],
  ["🎾","tennis"],
  ["🏐","volleyball"],
  ["🪁","kite"],
  ["🎮","game"],
  ["🎲","dice"],
  ["🧩","puzzle"],
  ["🧸","teddy"],
  ["🎈","balloon"],
  ["🎁","gift"],
  ["🎨","paint"],
  ["🎬","movie"],
  ["🎤","mic"],
  ["🎧","headphones"],
  ["🎹","piano"],
  ["🥁","drum"],
  ["🎷","sax"],
  ["🎺","trumpet"],
  ["🎸","guitar"],
  ["🎻","violin"],
  ["📖","book"],
  ["✏️","pencil"],
  ["🎒","bag"],
  ["👓","glasses"],
  ["👟","shoe"],
  ["🧢","hat"],
  ["👑","crown"],
  ["💍","ring"],
  ["⌚","watch"],
  ["📱","phone"],
  ["💻","computer"],
  ["📷","camera"],
  ["⏰","clock"],
  ["🔑","key"],
  ["💡","lamp"],
  ["🛏️","bed"],
  ["🪑","chair"],
  ["🚪","door"],
  ["🪟","window"],
  ["🧼","soap"],
  ["👧","girl"],
  ["👦","boy"],
  ["👩","woman"],
  ["👨","man"],
  ["👶","baby"]
];

  const WORD_BY_EMOJI = Object.fromEntries(PAIRS);

  const DEFAULT_WORDS = [
    {emoji:"🐶", word:"dog"},
    {emoji:"🐱", word:"cat"},
    {emoji:"🐟", word:"fish"},
    {emoji:"🐦", word:"bird"},
    {emoji:"🍎", word:"apple"},
    {emoji:"🍌", word:"banana"},
    {emoji:"🎂", word:"cake"},
    {emoji:"💧", word:"water"},
    {emoji:"☀️", word:"sun"},
    {emoji:"🌸", word:"flower"},
    {emoji:"🏠", word:"house"},
    {emoji:"⚽", word:"ball"},
    {emoji:"🚗", word:"car"},
    {emoji:"📖", word:"book"},
    {emoji:"👟", word:"shoe"},
    {emoji:"🌙", word:"moon"}
  ];

  global.PAIRS = PAIRS;
  global.WORD_BY_EMOJI = WORD_BY_EMOJI;
  global.DEFAULT_WORDS = DEFAULT_WORDS;
})(typeof window !== "undefined" ? window : (typeof globalThis !== "undefined" ? globalThis : this));
